apiVersion: v1
kind: Service
metadata:
  name: cowsay
  namespace: demoapp
spec:
  type: NodePort
  selector:
    app: demoapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007