apiVersion: v1
kind: Service
metadata:
  name: cowsay
  namespace: demoapp
spec:
  selector: cowsay
    app: demoapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
    nodePort: 30007